name: Analyze

on: workflow_dispatch

jobs:
  analyze:
    runs-on: titov-pionir
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Location
        run: pwd
      - name: Analyze
        run: python clang-analyzer.py main.cpp foo.cpp