name: Analyze

on: 
  - workflow_dispatch
  - push


jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Requirements
        run: python -m pip install dataclasses_json 
      - name: Path
        run: export PATH=$PATH:/usr/lib/llvm-12/bin
      - name: Check Path
        run: pwd
      - name: Analyze
        run: python clang-analyzer.py main.cpp foo.cpp
      - name: Upload results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with: 
          name: results.txt
          path: results.txt

  post-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Post Failure Test
        run: echo "I work"