name: Analyze

on: 
  - workflow_dispatch
  - push


jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Requirements
        run: python -m pip install dataclasses_json 
      - name: Path
        run: export PATH=$PATH:/usr/lib/llvm-12/bin
      - name: Analyze
        run: python clang-analyzer.py main.cpp foo.cpp