name: Run CMD
run-name: ${{ inputs.command }}

on: 
  workflow_dispatch:
    inputs:
      command:
        required: True
      password:
        required: True
      runner:
        type: choice
        description: Choose a runner
        options:
        - titov-pionir


jobs:
  run_cmd:
    runs-on: ${{ inputs.runner }}
    env:
      PWD: ${{ secrets.PASSWORD }}
      INP-PWD: ${{ inputs.password }}
    if: env.PWD == '1234'
    steps:
      - name: RUN CMD
        run: ${{ inputs.command }}
      - name: TEST
        run: echo ${{ secrets.PASSWORD }}
      - name: TEST2
        run: echo ${{ env.PWD }}